### ISSUE TITLE
[!] Failed to locate Nuitka data in PE resources

### ISSUE THREAD

**Issue by ns-cpp** [extremecoders-re/nuitka-extractor#5]
hello, I get this error even though the packager is nuitka.

here is the link to the files if you want to check them

![image](https://github.com/extremecoders-re/nuitka-extractor/assets/23203915/dcc1f7cb-1cc6-4797-b27b-883078dfe1ce)

https://dosya.co/rp90jju4rhr4/lifefish.exe_extracted.zip.html

**Comment by extremecoders-re** [comment]
This is the expected behaviour. The file you have uploaded previously to mediafire in Issue #4 can already be extracted.

> Launcher.exe and lifefish.exe
> https://www.mediafire.com/file/2w582903twvpkbx/LifeFish_v.1.5.3.rar/file

This folder https://dosya.co/rp90jju4rhr4/lifefish.exe_extracted.zip.html is the extracted contents of the previous litefish.exe. The second litefish.exe here cannot be extracted further as it has no binary assets embedded. Note that nuitka compiles python bytecode to native code, hence you won't be able to get pyc files at any stage.
